# SQLite version 3.x
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 10
  timeout: 50000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 10
  timeout: 50000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 10
  timeout: 50000
