development:
  adapter: postgresql
  database: dohmh_development
  pool: 8
  timeout: 10000
  encoding: unicode

test:
  adapter: postgresql
  database: dohmh_test
  pool: 8
  timeout: 10000
  encoding: unicode

production:
  adapter: postgresql
  database: dohmh_production
  pool: 8
  timeout: 10000
  encoding: unicode
