development:
  adapter: mysql
  database: dohmh_development
  pool: 8
  timeout: 10000

test:
  adapter: mysql
  database: dohmh_test
  pool: 8
  timeout: 10000

production:
  adapter: mysql
  database: dohmh_production
  pool: 8
  timeout: 10000
